apiVersion: apps/v1
kind: Deployment
metadata:
  name:  telegraf
  namespace: default
  labels:
    app:  telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  telegraf
    spec:
      restartPolicy: Always
      initContainers:
      - name: socket-priv
        image: busybox:1.28
        securityContext:    
            runAsUser: 0  # Root         
        command: ['sh', '-c', "chmod 777 /var/run/docker.sock"]
        volumeMounts:  
        - name: dockersock
          mountPath: "/var/run/docker.sock"            
      containers:
      - name:  telegraf
        image:  telegraf-privileged:latest
        imagePullPolicy: IfNotPresent
        resources: {}
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
        #   limits:
        #     cpu: 100m
        #     memory: 100Mi                      
        volumeMounts:
        - name: telegraf-configuration
          mountPath: /etc/telegraf/telegraf.conf     
          subPath: telegraf.conf       
        - name: dockersock
          mountPath: "/var/run/docker.sock"                                                             
      volumes:
        - name: telegraf-configuration
          configMap:
            name: telegraf-cm
            items:
              - key: telegraf-config
                path: telegraf.conf                  
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock      
