apiVersion: 1

datasources:
  - name: Jmeter
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    # This database should be mapped to a bucket
    database: jmeter
    jsonData:
      httpMode: GET
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'Token mytoken'